[package]
name = "pduel"
version = "0.1.0"
edition = "2024"

[dependencies]
curve25519-dalek = "4.1.3"
ed25519-dalek = "2.2.0"
hex = "0.4.3"
hex-literal = "1.1.0"
itertools = "0.14.0"
rand = "0.9.2"
sha2 = "0.10.9"
strum = { version = "0.27.2", features = ["derive"] }
